spring:
  profiles:
    active:
      - dev

logging:
  path: logs
server:
  port: 8100

---
spring:
  profiles: dev
  redis:
    host: localhost
    port: 6379
    database: 0
    pool:
      min-idle: 2

dber:
  upload:
    uploadExpireSeconds: 600
    downloadExpireSeconds: 3600
    tokenMaxSize: 10000
    callbackUrl: http://c1694f29.ngrok.io/pub/callback
    auth:
      accessKey: pRn3RLJX5dKttaGTICC4KHjxevhxDVwIgNTLF3a2
      secretKey: A5UDH6CUWJhwOkQJSZwQk-n5y9LOhEyjWl9iR9vU
    buckets:
      pub:
        name: dev-imge
        url: //p31z7ux9b.bkt.clouddn.com
        upUrl: //upload-z2.qiniup.com
      pri:
        name: dev-imge-
        url: //p320trfbx.bkt.clouddn.com
        upUrl: //upload-z2.qiniup.com
  auth:
#   授予权限
    grant:
      plat: 123
      bill: 123
      shop: 123
      customer: 123
      coacher: 123
#      获取权限
    obtain:
      plat: 123
      bill: 123
      shop: 123
      customer: 123
      coacher: 123
  service:
    name: upload
    database:
      host: localhost
      port: 3306
      database: dber_upload
      username: root
      password: cwl123
      parameters: characterEncoding=utf8&rewriteBatchedStatements=true&autoReconnect=true
      initialSize: 1
      maxActive: 2
      minIdle: 1
